name: DevSecOps Scan & Fix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    name: 🛡️ Skanowanie bezpieczeństwa
    runs-on: ubuntu-latest
    env:
      OWASP_DEP_CHECK_DIR: ./owasp-dependency-check-report
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      # Klonowanie repozytorium
      - name: Pobierz kod źródłowy
        uses: actions/checkout@v4

      # Ustawienie Node.js
      - name: Konfiguracja Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Ustawienie Pythona
      - name: Konfiguracja Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Instalacja zależności npm
      - name: Instalacja zależności npm
        run: npm install

      # Instalacja zależności pip
      - name: Instalacja zależności pip
        run: pip install -r requirements.txt || echo "Brak wymagań Pythona"

      # OWASP Dependency-Check
      - name: Skanowanie OWASP Dependency-Check
        uses: jeremylong/DependencyCheckAction@v3
        with:
          project: juice-shop-devsecops
          format: 'XML,HTML'
        continue-on-error: true

      # npm audit
      - name: Skanowanie npm audit
        run: npm audit --audit-level=moderate || true

      # pip-audit
      - name: Skanowanie pip-audit
        run: pip install pip-audit && pip-audit --fail-on high || true

      # Snyk
      - name: Skanowanie Snyk
        uses: snyk/actions/node@master
        with:
          command: test
          args: --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      # Semgrep
      - name: Skanowanie Semgrep
        uses: returntocorp/semgrep-action@v2
        with:
          config: auto
        continue-on-error: true

      # SonarQube
      - name: Skanowanie SonarQube
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectKey: ttomasze_juice-shop-devsecops
          organization: ttomasze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Bandit
      - name: Skanowanie Bandit (Python)
        run: |
          pip install bandit
          bandit -r . || true

      # Brakeman
      - name: Skanowanie Brakeman (Ruby on Rails)
        run: |
          gem install brakeman
          brakeman . || true

      # GitLeaks
      - name: Skanowanie GitLeaks (sekrety)
        uses: zricethezav/gitleaks-action@v2
        with:
          configPath: .gitleaks.toml
        continue-on-error: true

      # TruffleHog
      - name: Skanowanie TruffleHog (głębokie wyszukiwanie sekretów)
        uses: trufflesecurity/trufflehog-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      # OWASP ZAP
      - name: Skanowanie OWASP ZAP
        uses: zaproxy/action-baseline@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:3000'
          format: 'xml'
          output: 'zap-report.xml'
        continue-on-error: true

      # Uruchomienie aplikacji
      - name: Uruchomienie aplikacji (npm start)
        run: |
          npm start & sleep 30

      # Nikto
      - name: Skanowanie Nikto
        run: |
          sudo apt-get update && sudo apt-get install -y nikto
          nikto -h http://localhost:3000 -o nikto-report.txt
        continue-on-error: true

      # Archiwizacja raportów
      - name: Archiwizacja raportów bezpieczeństwa
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            owasp-dependency-check-report/
            zap-report.xml
            nikto-report.txt
            dependency-check-report.html

  auto_fix:
    name: 🔧 Automatyczne naprawy
    runs-on: ubuntu-latest
    needs: security
    steps:
      - name: Pobierz kod źródłowy
        uses: actions/checkout@v4

      - name: Konfiguracja Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalacja npm-check-updates
        run: npm install -g npm-check-updates

      - name: Aktualizacja zależności npm
        run: |
          ncu -u
          npm install
          git config user.name "ttomasze"
          git config user.email "ttomasze@gmail.com"
          git checkout -b deps-update || true
          git add package.json package-lock.json
          git commit -m "chore: aktualizacja zależności przez ncu" || echo "Brak zmian"
          git push --set-upstream origin deps-update || echo "Już wypchnięte"

      - name: Automatyczny merge PR z aktualizacją
        uses: pascalgn/automerge-action@v0.15.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
